---
openapi: 3.0.1
info:
  title: Task API
  version: v1
  description: API documentation for managing tasks
paths:
  "/api/v1/tasks":
    get:
      summary: List all tasks
      tags:
      - Tasks
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    due_date:
                      type: string
                      format: date_time
                  required:
                  - id
                  - title
                  - description
                  - status
    post:
      summary: Create a task
      tags:
      - Tasks
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                due_date:
                  type: string
                  format: date_time
              required:
              - title
              - description
              - status
  "/api/v1/tasks/{id}":
    parameters:
    - name: id
      in: path
      description: Task ID
      required: true
      schema:
        type: string
    get:
      summary: Retrieve a task
      tags:
      - Tasks
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  due_date:
                    type: string
                    format: date_time
                required:
                - id
                - title
                - description
                - status
        '404':
          description: not found
    patch:
      summary: Update a task
      tags:
      - Tasks
      parameters: []
      responses:
        '200':
          description: updated
        '422':
          description: unprocessable entity
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                due_date:
                  type: string
                  format: date_time
    delete:
      summary: Delete a task
      tags:
      - Tasks
      responses:
        '204':
          description: deleted
        '404':
          description: not found
servers:
- url: http://localhost:3000
  description: Local development server
